# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6716465d1525bb1e25315df3a143eb44f6a8dcb7d32b0c56593739381a8fd05872a1e4f6ca1524ccc79bc8f18b1e28e4994feca464b680dc589da020088c55f

test:
  secret_key_base: 43d5c770fa0d20f93ee2441fcb743ac2eb5624313e794a83b1955bcf76cd809ce69f44aea68eb8997a6383a8ce6d8adc1b53291e08a0a41f39b19a03fad18bda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
